Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0c94855ba95c71c99
      InstanceType: t2.micro
      KeyName: mykeypair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          echo "Hello World" > /var/www/html/index.html
  DBInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: "5.7"
      DBName: mydatabase
      MasterUsername: myusername
      MasterUserPassword: mypassword
      AllocatedStorage: 20
Outputs:
  EC2InstancePublicIP:
    Value: !GetAtt EC2Instance.PublicIp
  DBEndpoint:
    Value: !GetAtt DBInstance.Endpoint.Address
