name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create CloudFormation Stack
        uses: aws-actions/aws-cloudformation-deploy@v1.2.0
        with:
          stack-name: single-tier-app
          template: ./single-tier-app.yml
          capabilities: CAPABILITY_NAMED_IAM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Sync with S3 Bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
          source_dir: ./
        env:
          AWS_S3_BUCKET: my-static1-websit2e-bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
